# Generated by Django 4.2.6 on 2023-10-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalPostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostOfficeBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_info', models.CharField(max_length=100)),
                ('operating_hours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocalParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dimensions', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('international_post_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iposita_app.internationalpostoffice')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iposita_app.postofficebranch')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dimensions', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('international_post_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iposita_app.internationalpostoffice')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iposita_app.postofficebranch')),
            ],
        ),
        migrations.CreateModel(
            name='DriverTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('received', 'Received'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], max_length=20)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iposita_app.localparcel')),
            ],
        ),
    ]
