# Generated by Django 4.2.6 on 2023-10-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iposita_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=200)),
                ('sender_address', models.CharField(max_length=200)),
                ('sender_phone_number', models.CharField(max_length=200)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_email', models.EmailField(max_length=200)),
                ('recipient_address', models.CharField(max_length=200)),
                ('recipient_phone_number', models.CharField(max_length=200)),
                ('package_type', models.CharField(max_length=200)),
                ('package_destination', models.CharField(max_length=200)),
                ('package_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('branch', models.CharField(max_length=200)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('is_exception', models.CharField(choices=[('regular', 'regular'), ('exception', 'exception')], max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='internationalparcel',
            name='international_post_office',
        ),
        migrations.RemoveField(
            model_name='internationalparcel',
            name='post_office',
        ),
        migrations.RemoveField(
            model_name='localparcel',
            name='international_post_office',
        ),
        migrations.RemoveField(
            model_name='localparcel',
            name='post_office',
        ),
        migrations.DeleteModel(
            name='DriverTransaction',
        ),
        migrations.DeleteModel(
            name='InternationalParcel',
        ),
        migrations.DeleteModel(
            name='InternationalPostOffice',
        ),
        migrations.DeleteModel(
            name='LocalParcel',
        ),
        migrations.DeleteModel(
            name='PostOfficeBranch',
        ),
    ]
